### ISSUE TITLE
run_demo error

### ISSUE THREAD

**Issue by dongyy1148** [osrf/car_demo#64]
Hi osrf team,
When I run run_demo.bash, it gives me this
![image](https://user-images.githubusercontent.com/43221681/60122731-d4378980-9753-11e9-817e-cd637ac6a8c6.png)

Could you help figure this out? Thanks!

**Comment by sloretz** [comment]
Hi @dongyy1148, please copy and paste text in the description instead of providing a picture. When others have the same problem, they will be able to search by text and find the same answer.

If rocker is not found it likely means it needs to be installed. Make sure you've installed all the [requirements](https://github.com/osrf/car_demo#requirements). See the [rocker installation page](https://github.com/osrf/rocker#installation) for instructions.

I'll close this assuming the question is answered. It can be reopened if that's not the case.
